make: Improved check for llvm-config
phate/jlm pull request #112
Opened 2022-02-21 10:57 UTC by sjalander

2022-02-21 19:59 UTC, phate requested changes

2022-02-21 19:59 UTC, phate commented on Makefile.sub
> +  $(info Did not find llvm-config or llvm-config-13 and LLVMCONFIG is not specified)
llvm-config-13 should be llvm-config-11

2022-02-22 05:17 UTC, sjalander commented
Fixed the typo

2022-02-22 17:54 UTC, phate approved these changes

2022-02-22 17:55 UTC, merged