Add command line flags to jlm-opt to use Andersen for memory state encoding
phate/jlm pull request #301
Opened 2023-12-05 09:44 UTC by haved

Builds on top of #298 #299 #300

Adds the flags `-AAAndersenAgnostic` and `-AAAndersenRegionAware` to `jlm-opt`, mirroring the corresponding Steensgaard flags, with the only difference being the implementations of `AliasAnalyis` being used.

Feel free to suggest a nicer command line interface for specifying these things, as this was the most direct and straightforward method I could think of.

2023-12-09 05:51 UTC, phate requested changes

2023-12-09 05:51 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> +#include "AliasAnalysis.hpp"
`#include <>`

2023-12-09 05:51 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> +template<typename AliasAnalysisPass, bool regionAware>
Why using the bool? Why not handing in the provisioning pass directly, similarly to the alias analysis pass?

2023-12-09 05:51 UTC, phate commented on jlm/tooling/Command.cpp
> +#include <jlm/llvm/opt/alias-analyses/AliasAnalysis.hpp>
Why is this needed here? The only change is the inclusion of the header

2023-12-09 05:51 UTC, phate commented on jlm/tooling/CommandLine.cpp
> +              "Andersen alias analysis with region-aware memory state encoding"),
Could we push this over the Steensgaard flags such that they are sorted alphabetically in the `jlm-opt --help` output?

2023-12-12 04:19 UTC, phate requested changes
Mostly cleaning up after the Andersen alias analysis got merged.

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/Andersen.cpp
> +/*
Should be removed from this PR.

2023-12-12 04:19 UTC, phate commented on jlm/llvm/Makefile.sub
> +    jlm/llvm/opt/alias-analyses/Andersen.cpp \
Should be removed from this PR.

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/Andersen.hpp
> +/*
Should be removed from this PR.

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> + * the memory nodes provided by the memory node provided
"and the memory nodes provided by the memory node providerR"

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> + * to reencode memory state edges beteen the operations touching memory.
"betWeen"

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> +class MemoryStateEncodingPass final : public optimization
I am not fully sold on the name "MemoryStateEncodingPass". I am somehow bothered by the suffix "Pass" here, but I have also a hard time coming up with something better. Maybe AliasAnalysisStateEncoder?

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> +class MemoryStateEncodingPass final : public optimization
Leave it if you do not like AliasAnalysisStateEncoder and nothing else comes to your mind.

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
>    return PointerObjects_.size() - 1;
Should be removed from this PR.

2023-12-12 04:19 UTC, phate commented on jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
> +  [[nodiscard]] PointerObject::Index
Should be removed from this PR.

2023-12-12 04:19 UTC, phate commented on tests/jlm/llvm/opt/alias-analyses/Makefile.sub
> +	jlm/llvm/opt/alias-analyses/TestAndersen \
Should be removed from this PR.

2023-12-12 04:19 UTC, phate commented on tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
> +/*
Should be removed from this PR.

2023-12-13 21:06 UTC, haved commented
Merging with both the old branch and master resolved all the extra changes not part of this PR.
I used the name you suggested, I liked it very well, and was not really happy with the old one.

I also moved AAAndersen above AASteensgaard in all the places they are listed, for consistency.

2023-12-13 22:01 UTC, phate approved these changes
Solid work. Thanks a lot!

2023-12-13 22:01 UTC, merged