Add method for dumping the constraint set as a subset graph
phate/jlm pull request #437
Opened 2024-04-11 13:48 UTC by haved

Also adds some utility functions to the GraphWriter classes, to make it nicer to use. At first I was surprised that `arrowtail` is completely ignored when edges have their default `dir=forward`, so it now selects a `dir` that makes manually specified arrows heads visible.

The subset graphs produced look like
![image](https://github.com/phate/jlm/assets/3748845/f7c48558-1f50-4368-903f-e8df11343551)

Regular edges are superset constraints, dashed edges are complex constraints (dereference the side with the circle to convert it into a regular superset constraint edge).
The + means points to escaped, e means all the pointees in the set should escape. NOTRACK is for PointerObjects where the final PointsToGraph node doesn't get any pointees. Function call constraints don't use edges, so they are a bit harder to read.

For this PR, I have added another temporary environment variable `JLM_ANDERSEN_DUMP_SUBSET_GRAPH`, to enable dumping of the subset graph before and after solving. I don't imagine it will ever make sense to make it a proper command line option, so taking the ENV approach seemed the most sensible.

2024-04-12 04:06 UTC, phate requested changes
Looks overall good, but I would still like to have a unit test on the `DrawSubsetGraph()` method as well as some splitting up in individual functions maybe.

2024-04-12 04:06 UTC, phate commented on jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
> +
Could we also add a default case with `JLM_UNREACHABLE()` here?

2024-04-12 04:06 UTC, phate commented on jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
> +  DrawSubsetGraph(jlm::util::GraphWriter & writer) const;
Could we get a unit test on this method? That is one of the big benefits of the internal dot representation. Let's make use of it.

2024-04-12 16:46 UTC, haved commented on tests/jlm/util/TestGraphWriter.cpp
> +  assert(!graph.RemoveAttribute("colour"));
No, just me doing different spellings on purpose. I will make it clearer that they are supposed to be different.

2024-04-17 11:52 UTC, haved commented
I think all your comments should be addressed now, @phate. I had to add some methods to the GraphWriter, but I agree that being able to programatically inspect the graph is helpful for tests.

2024-04-18 04:38 UTC, phate commented
@haved Could it be that you forgot to push your changes? I do not see any changes after my comments except a merge from master.

2024-04-19 06:37 UTC, haved commented
@phate You are absolutely correct, It should be fixed now

2024-04-19 08:57 UTC, phate approved these changes
Approved as I do not want to delay this PR any longer.

The one thing I noticed is that magic constants are distributed throughout the code. Generally, they should be assigned to a static variable and the variable should then be used. In particular, if they are used at multiple places such as "arrowhead" (GraphWriter.cpp:985 and 1004), "arrowtail" (GraphWriter.cpp:992, 1005). I sadly did not catch this in the first review.

2024-04-19 21:39 UTC, haved commented
True, you bring up a good point, there are quite a few string literals, many of which are repeated. I will merge this for now, but I would like to clean some of it up later. I originally felt like adding a GetStyle() method for extracting the "style" attribute could be seen as overkill, but maybe you think it's actually fine @phate?

2024-04-19 21:39 UTC, merged

2024-04-20 04:50 UTC, phate commented
@haved I do not see a `GetStyle()` method. Did you mean `SetStyle()`? If so, I do not see a problem with this method. Am I missing something?

We currently hand also all the arguments as strings in. I would rather have enumerations and then internally translate them, but that is another issue.

2024-04-20 07:38 UTC, haved commented
@phate No I meant `GetStyle()`, which currently does not exist. The tests do `GetAttribute("style")` to extract the style, but the existence of `SetStyle()` maybe implies there should be a corresponding `GetStyle()`.