HLS backend update
phate/jlm pull request #445
Opened 2024-04-19 09:22 UTC by sjalander

The HLS backend has been worked on independently of the master branch. This commit is to bring the updated HLS backend up to date with master.
NB! This PR should not be merged until the jlm-eval-suite has been updated such that a proper commit can be used for the HLS CI.

To achieve this, the following three commits that are currently part of the master branch has not been applied to the HLS backend. These commits should be updated and applied at a later time.

beff174d657d4df27a51a5e4371ef8171664f4fb
Clean up HLS unused state removal transformation (#293)

92c65e65c9b533a708cdbd8fe06db6462e332124
Clean up HLS dead node elimination transformation (#294)

33580bba4475ba1f93462a0414fa5a1da9a78395
Clean up HLS gamma conversion (#291)

2024-04-19 10:12 UTC, phate commented
@sjalander It is not even compiling.

2024-04-19 12:35 UTC, sjalander commented
@phate I don't know why the CI performs more stringent source code checks, e.g., unused variables, than my local setup on Idun.
There are unfortunately new memory leaks and I currently don't have more time to spend on this.

2024-04-19 12:45 UTC, phate commented
@sjalander I can take a look eventually.

2024-04-20 03:40 UTC, phate commented
@sjalander It is not just valgrind that is complaining, but also the HLS test suite acts up.

2024-05-02 12:03 UTC, sjalander commented
@phate That's a known issue by the builders on github that seems to run out of resources for histogram. I'll take that test out in jlm-eval-suite

2024-05-08 02:58 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> +#include <jlm/llvm/opt/alias-analyses/MemoryNodeProvider.hpp>
@sjalander Is this include really necessary. I have my doubts about it.

2024-05-08 03:01 UTC, phate commented on jlm/llvm/opt/alias-analyses/Optimization.hpp
> +#include <jlm/llvm/opt/alias-analyses/MemoryNodeProvider.hpp>
Nevermind, looking closer at it, I think it is necessary.

2024-05-08 04:30 UTC, phate commented
@sjalander Since the valgrind issue is resolved now, could you create a PR with the other left-over new files?

2024-05-09 19:57 UTC, phate requested changes
@sjalander: Can we clarify what it is about `mem-conv.cpp`? There is a cpp file, but no header. Does this mean that this pass is not used and can be removed? Is the header only missing?

2024-05-09 20:07 UTC, sjalander commented
@phate mem_conv.hpp was included by mistake in the first PR that added files, i.e., it's already in master.

2024-05-09 20:11 UTC, sjalander commented on jlm/hls/Makefile.sub
> +	jlm/hls/backend/rvsdg2rhls/mem-conv.hpp \
mem-conv.hpp is already in master

2024-05-09 21:20 UTC, phate approved these changes

2024-05-09 21:45 UTC, merged