Adds HLS files that previously were missed
phate/jlm pull request #474
Opened 2024-05-08 17:22 UTC by sjalander

2024-05-08 18:16 UTC, phate requested changes
Looking at the other HLS PR, I would have expected the following files in this PR:

1. dae-conv.[ch]pp
2. instrument-ref.[ch]pp
3. mem-conv.cpp. There exists no mem-conv.hpp in the other PR. However, the mem-conv.hpp is mentioned in the Makefile there.
4. rhls-dne.[ch]pp

Number 1 and 4 are here. Number 2 is missing. Any reason? Number 3 is also missing, as well as the hpp file from the other PR.

2024-05-08 18:16 UTC, phate commented on jlm/hls/Makefile.sub
> +	jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.hpp \
This file does not exist in the PR.

2024-05-08 18:16 UTC, phate commented on jlm/hls/Makefile.sub
> +	jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.hpp \
Okay, this file already exists in the repository, but is just not mentioned here.

2024-05-08 18:19 UTC, phate commented on jlm/hls/Makefile.sub
> +	jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.hpp \
Ignore the above comments.

2024-05-09 06:27 UTC, sjalander commented
They require modifications to jlm/hls/ir/hls.[hc]pp
So this PR only contains files that does not require modifications of already committed files.

2024-05-09 12:13 UTC, phate approved these changes

2024-05-09 12:13 UTC, merged