[Andersen] Add online cycle detection
phate/jlm pull request #495
Opened 2024-05-29 15:00 UTC by haved

Adds Online Cycle Detection described by Pearce et al. "Online cycle detection and difference propagation for pointer analysis" (2003).

OCD is enabled by default, but can be controlled by the config environment variable. Template fun is used to dispatch the runtime boolean into a compile time boolean, so there is no performance hit when OCD is disabled.

Also contains a fix for a bug that could occur when the Escaped-flag implies PointsToExternal in the unification root, without adding the unification root to the worklist. I had handled this for PointeesEscaping already, just forgot PointsToExternal.

2024-05-29 22:28 UTC, phate requested changes
This stuff is clearly tricky. I hope some of my comments make sense.

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
> +    constexpr bool EnableOnlineCycleDetection = decltype(onlineCycleDetection)::value;
`enableOnlineCycleDetection`

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +   * A assigns each unification root a position in a topological ordering.
Did you mean: `Assigns each unification...`

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +    std::vector<size_t> sccIndex;
`std::vector<PointerObjectIndex> sccIndex`

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +    std::vector<size_t> topologicalOrder;
same here, no?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +      }
Introduce a variable `nextIndex = i + 1` (or a more suitable name) and use this one instead of the `i +1`s all of over the place.

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +#endif
Change the method to: `bool HasValidTopologicalOrder()` and change this line to `JLM_ASSERT(HasValidTopologicalOrder())`

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +          continue;
Are the comments misleading or is something off here? How can it be that this is the firstVisit and then we check whether the node has already been visited?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +        // Push all non-pushed successors with topo within [lowerTopo, upperTopo]
`with topo within`: I have no idea what that means.

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +          optUnificationRoot = node;
ternary operator maybe?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +    for (int64_t i = lowerTopo; i <= upperTopo; i++)
`auto`?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +#endif
same as above

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +  ValidateTopologicalOrder()
Does this function need to be public or can it be made private?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +        JLM_ASSERT(ObjectToTopoOrder_[successorRoot] > topo);
This is now the second or third time I see this little code snippet. Could you introduce a little method that takes two parameters and checks these invariants, and then use this here with `JLM_ASSERT()`?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +  std::vector<PointerObjectIndex> DfsSupersetAndBeyond_;
Could we get some empty lines between the declarations and the next comment?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +  // Data structures used by to store state during DFS passes are kept here,
`used to .....`, remove `by`

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/Andersen.hpp
> +     * Enables or disables online cycle detection in the Worklist solver, as described by.
`as described by....` what?

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/Andersen.hpp
> +    EnableOnlineCycleDetection(bool enable)
`noexcept`

2024-05-29 22:28 UTC, phate commented on jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
> +  auto DispatchOCD = [&](auto onlineCycleDetection)
`DispatchOnlineCycleDetection()`

2024-05-30 09:09 UTC, haved commented on jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
> +    const auto nonRoot = aRoot + bRoot - root;
since root is either aRoot or bRoot, the expression finds the "opposite" of root. I can replace it with a ternary instead.

2024-05-30 13:04 UTC, haved commented
@phate I implemented your suggested changes and wrote more detailed comments in the places you were unsure about

2024-05-30 17:13 UTC, phate approved these changes
Thanks for making the changes, it is more readable now. I have another go at it and added some more suggestions, but won't block it any longer. Up to you.

Great job!

2024-05-30 17:13 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +    DfsCycleNodes_.Clear();
If I understand this correctly, then these methods are only here to ensure that multiple invocations of method can operate correctly. Maybe you can push all these lines in a private method `ClearInternalState()` and invoke it here.

2024-05-30 17:13 UTC, phate commented on jlm/llvm/opt/alias-analyses/OnlineCycleDetection.hpp
> +    DfsSupersetAndBeyond_.clear();
This method can also be pushed in the `ClearInternalState()` method, no? I do not see `DfsSupersetAndBeyond` used before this line.

2024-05-30 21:07 UTC, haved commented
@phate I implemented your comments, and moved from using -1 to `numeric_limits::max()`, to avoid needing signed int64s.

2024-05-30 21:15 UTC, phate approved these changes

2024-05-30 21:32 UTC, merged