Move CFG conversion to ascii to cfg class
phate/jlm pull request #631
Opened 2024-09-20 04:49 UTC by phate

The ascii output for the control flow graph is not easily readable. This is the first PR on improving it. It does the following:

1. Moves the functions for converting a CFG to ascii to the cfg class
2. Adds a unit test for the conversion of three address codes

In order to add a unit test for the CFG conversion, I first need to make the output more deterministic. This will happen in a follow up PR. This PR is part of issue #586

2024-09-20 11:50 UTC, haved requested changes
Looks good, just a wrong name in the Copyright header

2024-09-20 11:50 UTC, haved commented on tests/jlm/llvm/ir/ThreeAddressCodeTests.cpp
> + * Copyright 2024 Håvard Krogstie <krogstie.havard@gmail.com>
Yourself?

2024-09-28 04:57 UTC, phate commented on tests/jlm/llvm/ir/ThreeAddressCodeTests.cpp
> + * Copyright 2024 Håvard Krogstie <krogstie.havard@gmail.com>
Done.

2024-09-28 05:24 UTC, haved approved these changes

2024-09-28 05:49 UTC, merged