theta: change API for mapping loop variables
phate/jlm pull request #675
Opened 2024-12-02 20:50 UTC by caleridas

Provide an API to loop nodes that allows mapping the various representation pieces of a loop variable. Remove
Theta{Input|Output|Argument|Result}.

2024-12-02 20:54 UTC, caleridas commented
This change again provides names for variable roles that may be controversial:

- I picked "pre/post" to designate the places of the variables at loop start and end as pre/post are fairly short
- more precisely, they could be called "preIter" / "postIter" or similar, but that may be too verbose
- I also considered "entry" resp. "exit" as names; however they are too ambiguous IMHO as they could be construed to mean the "one time" loop entry / exit values (i.e. before first and after last iteration)
- unlike gamma where there is no such ambiguity with argument / result, the same ambiguity for argument / result exists as for entry / exit

2024-12-04 05:57 UTC, phate requested changes
Looks all good to me. I am fine with the names, even though `preIteration` and `postIteration` would be a bit more descriptive, but is also quite long.

2024-12-04 05:57 UTC, phate commented on jlm/rvsdg/theta.hpp
> +class ThetaResult;
You just removed these classes below. These forward declarations can be removed as well, no?

2024-12-04 05:57 UTC, phate commented on jlm/rvsdg/theta.hpp
> +  AddLoopVar(rvsdg::output * origin);
Could we get some documentation on it?

2024-12-04 05:57 UTC, phate commented on jlm/rvsdg/theta.cpp
> +
Can be removed. Does not add any value

2024-12-04 05:57 UTC, phate commented on jlm/rvsdg/theta.cpp
> +  auto nf = graph()->node_normal_form(typeid(jlm::rvsdg::operation));
`rvsdg::operation`

2024-12-04 05:57 UTC, phate commented on jlm/rvsdg/theta.hpp
> +  std::vector<std::size_t> unmatchedOutputs;
Is this really necessary? The only places where theta variables are removed should be DNE, and there we use the `RemoveThetaInputsWhere` and `RemoveThetaOutputsWhere` immediately after each other to ensure that the inconsistent state is very local. Where else are theta inputs/outputs are removed such that this becomes necessary?

2025-01-03 20:01 UTC, caleridas commented on jlm/rvsdg/theta.hpp
> +  std::vector<std::size_t> unmatchedOutputs;
I don't like this, and I have a proposal how to do it better, but I would like to separate this from the present PR:

Outputs that are deemed to be "dead" do not play a role in computation, so we are allowed to assign an arbitrary value to it. So instead of leaving unbalanced inputs/outputs we can always route the pre-loop value through to satisfy it. Then, in a second step, we can eliminate them as loop-invariant, and unused inside the loop. This way we avoid ever having unbalanced inputs/outputs, but the tracking of trying to eliminate them needs to move into DNE.

2025-01-03 20:15 UTC, caleridas commented
I have a hard time interpreting the failure from the hls test suite. On github I have no clear indication what exactly fails and when I run it locally, I get this:

Building: base/test_return
Building: base/test_arithmetic
Building: base/test_array
Building: base/test_conditional
Building: base/test_load
Building: base/test_gep
Building: base/test_loop
Building: base/test_nested_loops
Building: base/test_global
Building: base/test_matrix
Building: base/test_cpu
Building: benchmarks/DSS/smm
Building: benchmarks/DSS/getTanh
Building: benchmarks/Inter-block/matrixtrans
Building: benchmarks/Inter-block/substring
Building: benchmarks/PNAnalyser/vecTrans
Building: benchmarks/PNAnalyser/vecTrans2
Building: polybench/jacobi_1d
Building: polybench/correlation
Building: dynamatic/fir
Building with gcc: dynamatic/fir
Building: dynamatic/gaussian
Building with gcc: dynamatic/gaussian
Building: dynamatic/if_loop_1
Building with gcc: dynamatic/if_loop_1
Building: dynamatic/if_loop_2
Building with gcc: dynamatic/if_loop_2
Building: dynamatic/if_loop_3
Building with gcc: dynamatic/if_loop_3
Building: dynamatic/iir
Building with gcc: dynamatic/iir
Building: dynamatic/image_resize
Building with gcc: dynamatic/image_resize
Building: dynamatic/insertion_sort
Building with gcc: dynamatic/insertion_sort
Building with gcc: dynamatic/kernel_2mm
Building: dynamatic/kernel_2mm
Building: dynamatic/kernel_3mm
Building with gcc: dynamatic/kernel_3mm
Building: dynamatic/loop_array
Building with gcc: dynamatic/loop_array
Building: dynamatic/matrix
Building with gcc: dynamatic/matrix
Building: dynamatic/memory_loop
Building with gcc: dynamatic/memory_loop
Building: dynamatic/mul_example
Building with gcc: dynamatic/mul_example
Building: dynamatic/pivot
Building with gcc: dynamatic/pivot
Building: dynamatic/simple_example_1
Building with gcc: dynamatic/simple_example_1
Building: dynamatic/simple_example_2
Building with gcc: dynamatic/simple_example_2
Building with gcc: dynamatic/stencil_2d
Building: dynamatic/sumi3_mem
Building: dynamatic/stencil_2d
Building with gcc: dynamatic/sumi3_mem
Building: dynamatic/test_memory_1
Building with gcc: dynamatic/test_memory_1
Building: dynamatic/test_memory_2
Building with gcc: dynamatic/test_memory_2
Building: dynamatic/test_memory_3
Building with gcc: dynamatic/test_memory_3
Building: dynamatic/test_memory_4
Building with gcc: dynamatic/test_memory_4
Building with gcc: dynamatic/test_memory_6
Building: dynamatic/test_memory_6
Building: dynamatic/test_memory_7
Building with gcc: dynamatic/test_memory_7
Building: dynamatic/test_memory_8
Building with gcc: dynamatic/test_memory_8
Building: dynamatic/test_memory_9
Building with gcc: dynamatic/test_memory_9
Building: dynamatic/test_memory_10
Building with gcc: dynamatic/test_memory_10
Building: dynamatic/test_memory_11
Building with gcc: dynamatic/test_memory_11
Building: dynamatic/test_memory_12
Building with gcc: dynamatic/test_memory_12
Building: dynamatic/test_memory_13
Building with gcc: dynamatic/test_memory_13
Building: dynamatic/test_memory_14
Building with gcc: dynamatic/test_memory_14
Building: dynamatic/test_memory_15
Building with gcc: dynamatic/test_memory_15
Building: dynamatic/test_memory_16
Building with gcc: dynamatic/test_memory_16
Building with gcc: dynamatic/test_memory_17
Building: dynamatic/test_memory_17
Building: dynamatic/test_memory_18
Building with gcc: dynamatic/test_memory_18
Building: dynamatic/threshold
Building with gcc: dynamatic/threshold
Building: dynamatic/vector_rescale
Building with gcc: dynamatic/vector_rescale
Building: dynamatic/video_filter
Building with gcc: dynamatic/video_filter
Building: dynamatic/bicg
Building with gcc: dynamatic/bicg
Building: dynamatic/gemver
Building with gcc: dynamatic/gemver
Building: dynamatic/matrix_power
Building with gcc: dynamatic/matrix_power
Building: dynamatic/matvec
Building with gcc: dynamatic/matvec
Building: dynamatic/triangular
Building with gcc: dynamatic/triangular
Building: dynamatic/binary_search
Building with gcc: dynamatic/binary_search
Building: dynamatic/gcd
Building with gcc: dynamatic/gcd
Building with gcc: dynamatic/polyn_mult
Building: dynamatic/polyn_mult
Building with gcc: dynamatic/sobel
Running: base/test_return
Running: base/test_arithmetic
Running: base/test_loop
Running: base/test_nested_loops
Running: base/test_conditional
Running: base/test_load
Running: base/test_array
Running: base/test_gep
Building: dynamatic/sobel
Running: base/test_global
Running: base/test_matrix
Running: base/test_cpu
Running: benchmarks/DSS/getTanh
Running: benchmarks/DSS/smm
Running: benchmarks/Inter-block/matrixtrans
Running: benchmarks/PNAnalyser/vecTrans
Running: benchmarks/PNAnalyser/vecTrans2
Running: polybench/jacobi_1d
Running: dynamatic/fir
Running: dynamatic/gaussian
Running: dynamatic/if_loop_1
Running: dynamatic/if_loop_2
Running: dynamatic/if_loop_3
Running: dynamatic/iir
Running: dynamatic/image_resize
Running: dynamatic/insertion_sort
Running: dynamatic/kernel_2mm
Running: dynamatic/kernel_3mm
Running: dynamatic/loop_array
Running: dynamatic/matrix
Running: dynamatic/memory_loop
Running: dynamatic/mul_example
Running: dynamatic/pivot
Running: dynamatic/simple_example_1
Running: dynamatic/simple_example_2
Running: dynamatic/stencil_2d
Running: dynamatic/sumi3_mem
Running: dynamatic/test_memory_1
Running: dynamatic/test_memory_2
Running: dynamatic/test_memory_3
Running: dynamatic/test_memory_4
Running: dynamatic/test_memory_6
Running: dynamatic/test_memory_7
Running: dynamatic/test_memory_8
Running: dynamatic/test_memory_9
Running: dynamatic/test_memory_10
Running: dynamatic/test_memory_11
Running: dynamatic/test_memory_12
Running: dynamatic/test_memory_13
Running: dynamatic/test_memory_14
Running: dynamatic/test_memory_15
Running: dynamatic/test_memory_16
Running: dynamatic/test_memory_17
Running: dynamatic/test_memory_18
Running: dynamatic/threshold
Running: dynamatic/vector_rescale
Running: dynamatic/video_filter
Running: dynamatic/bicg
Running: dynamatic/gemver
Running: dynamatic/matrix_power
Running: dynamatic/matvec
Running: dynamatic/triangular
Running: dynamatic/binary_search
Running: dynamatic/gcd
The execution time of base/test_matrix has changed
    Golden cycle time: 571
    Simulated cycles: 588
The execution time of dynamatic/test_memory_7 has changed
    Golden cycle time: 52
    Simulated cycles: 31
    SUCCESS: base/test_return
    SUCCESS: base/test_arithmetic
    SUCCESS: base/test_loop
    SUCCESS: base/test_nested_loops
    SUCCESS: base/test_conditional
    SUCCESS: base/test_load
    SUCCESS: base/test_array
    SUCCESS: base/test_gep
    SUCCESS: base/test_global
    SUCCESS: base/test_matrix
    SUCCESS: base/test_cpu
    SUCCESS: benchmarks/DSS/getTanh
    SUCCESS: benchmarks/DSS/smm
    SUCCESS: benchmarks/Inter-block/matrixtrans
    SUCCESS: benchmarks/PNAnalyser/vecTrans
    SUCCESS: benchmarks/PNAnalyser/vecTrans2
    SUCCESS: polybench/jacobi_1d
    SUCCESS: dynamatic/fir
    SUCCESS: dynamatic/gaussian
    SUCCESS: dynamatic/if_loop_1
    SUCCESS: dynamatic/if_loop_2
    SUCCESS: dynamatic/if_loop_3
    SUCCESS: dynamatic/iir
    SUCCESS: dynamatic/image_resize
    SUCCESS: dynamatic/insertion_sort
    SUCCESS: dynamatic/kernel_2mm
    SUCCESS: dynamatic/kernel_3mm
    SUCCESS: dynamatic/loop_array
    SUCCESS: dynamatic/matrix
    SUCCESS: dynamatic/memory_loop
    SUCCESS: dynamatic/mul_example
    SUCCESS: dynamatic/pivot
    SUCCESS: dynamatic/simple_example_2
    SUCCESS: dynamatic/simple_example_1
    SUCCESS: dynamatic/sumi3_mem
    SUCCESS: dynamatic/stencil_2d
    SUCCESS: dynamatic/test_memory_1
    SUCCESS: dynamatic/test_memory_2
    SUCCESS: dynamatic/test_memory_3
    SUCCESS: dynamatic/test_memory_4
    SUCCESS: dynamatic/test_memory_6
    SUCCESS: dynamatic/test_memory_7
    SUCCESS: dynamatic/test_memory_8
    SUCCESS: dynamatic/test_memory_9
    SUCCESS: dynamatic/test_memory_10
    SUCCESS: dynamatic/test_memory_11
    SUCCESS: dynamatic/test_memory_12
    S [...]

2025-01-03 20:22 UTC, caleridas commented
I tried pushing a change to hls-test-suite:

--- a/src/base/test_matrix.cycles
+++ b/src/base/test_matrix.cycles
@@ -1 +1 @@
-571
\ No newline at end of file
+588
\ No newline at end of file
diff --git a/src/dynamatic/test_memory_7.cycles b/src/dynamatic/test_memory_7.cycles
index 6139554..b74e882 100644
--- a/src/dynamatic/test_memory_7.cycles
+++ b/src/dynamatic/test_memory_7.cycles
@@ -1 +1 @@
-52
\ No newline at end of file
+31
\ No newline at end of file
diff --git a/src/polybench/correlation.cycles b/src/polybench/correlation.cycles
index 9ad41b4..b45d0b7 100644
--- a/src/polybench/correlation.cycles
+++ b/src/polybench/correlation.cycles
@@ -1 +1 @@
-185779
\ No newline at end of file
+178462
\ No newline at end of file

but I lack permission to create a branch on that repository.

2025-01-03 22:51 UTC, phate commented on jlm/rvsdg/theta.hpp
> +  std::vector<std::size_t> unmatchedOutputs;
@caleridas Sounds reasonable to me. I will mark this conversation as resolved then. I would like you to push this fix for the imbalance then rather soon though such that we do not have the code above lingering around for too long.

2025-01-03 22:54 UTC, phate commented
@caleridas I invited you the llvm-test-suite repository and the hls-test-suite repository as collaborator. I leave the issues with the HLS test suite to @sjalander to answer, he knows way more about it than I do.

2025-01-04 15:15 UTC, sjalander commented
> While I do not understand why my change causes semantic change to the compilation pipeline, I am a bit wondering whether this causes a "semantically meaningful" change to the compilate, or whether the change is fine and the test is a bit too change-sensitive. How would I distinguish between these? @sjalander @phate

I assume you refer to the changes in cycle count. I think at the moment, it's only @davidmetz that might be able to answer this. But I believe that some optimizations are based on heuristics or pattern matching, and a change to the graph can "enable/disable" an optimization to be applied.
The cycle count check was added such that we do not inadvertently hurt the performance of the HLS backend. I didn't expect the cycle count to change that often, so initially it was set to cause the test suite to fail. This has been changed such that it now only prints the difference. That way, we at least have a history of CI actions that can be used to track down PRs that might have caused a larger performance penalty. @caleridas

2025-01-04 15:20 UTC, sjalander commented
The HLS test suite fails because of two JLM_ASSERTS that doesn't seem to hold any longer with the changes made to the theta in this PR. 

When I comment out the two JLM_ASSERT on line 190 and 544 in jlm/hls/opt/cne.cpp, then the test suite passes. @caleridas

2025-01-04 20:33 UTC, caleridas commented
> > While I do not understand why my change causes semantic change to the compilation pipeline, I am a bit wondering whether this causes a "semantically meaningful" change to the compilate, or whether the change is fine and the test is a bit too change-sensitive. How would I distinguish between these? @sjalander @phate
> 
> I assume you refer to the changes in cycle count. I think at the moment, it's only @davidmetz that might be able to answer this. But I believe that some optimizations are based on heuristics or pattern matching, and a change to the graph can "enable/disable" an optimization to be applied. The cycle count check was added such that we do not inadvertently hurt the performance of the HLS backend. I didn't expect the cycle count to change that often, so initially it was set to cause the test suite to fail. This has been changed such that it now only prints the difference. That way, we at least have a history of CI actions that can be used to track down PRs that might have caused a larger performance penalty. @caleridas

Thanks for the explanation, I understand the need to catch regressions and do not mind having the cycle count checked as a proxy, but I was primarily wondering about the "procedure" to follow here. If adjusting golden set occasionally after manually verifying that the change is "okay" then this is perfectly reasonable, question is what exactly is "okay" and how to determine. Intuitively I assume in this case the way the counts changed should not indicate major regression, but wanted to clarify.

2025-01-04 20:44 UTC, caleridas commented
> The HLS test suite fails because of two JLM_ASSERTS that doesn't seem to hold any longer with the changes made to the theta in this PR.
> 
> When I comment out the two JLM_ASSERT on line 190 and 544 in jlm/hls/opt/cne.cpp, then the test suite passes. @caleridas

Missed that error, checking debug compile.

2025-01-04 22:57 UTC, caleridas commented
> > The HLS test suite fails because of two JLM_ASSERTS that doesn't seem to hold any longer with the changes made to the theta in this PR.
> > When I comment out the two JLM_ASSERT on line 190 and 544 in jlm/hls/opt/cne.cpp, then the test suite passes. @caleridas
> 
> Missed that error, checking debug compile.

Found and fixed logic bug introduced into CNE. Now, the cycle time changes is also smaller.

2025-01-05 08:18 UTC, caleridas commented on jlm/rvsdg/theta.hpp
> +  AddLoopVar(rvsdg::output * origin);
done

2025-01-05 08:18 UTC, caleridas commented on jlm/rvsdg/theta.cpp
> +
done

2025-01-05 08:19 UTC, caleridas commented on jlm/rvsdg/theta.cpp
> +  auto nf = graph()->node_normal_form(typeid(jlm::rvsdg::operation));
outdated

2025-01-05 08:19 UTC, caleridas commented on jlm/rvsdg/theta.hpp
> +  std::vector<std::size_t> unmatchedOutputs;
okay resolving this for now and looking at CNE

2025-01-05 08:20 UTC, caleridas commented on jlm/rvsdg/theta.hpp
> +class ThetaResult;
removed

2025-01-05 12:33 UTC, caleridas commented
It turns out that the required change to dead node elimination to cleanly handle theta _without_ ever requiring unbalanced inputs/outputs is fairly straight-forward: 
https://github.com/phate/jlm/commit/dece50b6fa91f6c52431d6df2abf02200e6c2e41

I could as well consider putting it into this branch and do the complete thing with a single PR, just let me know @phate

2025-01-05 16:14 UTC, sjalander commented
> Thanks for the explanation, I understand the need to catch regressions and do not mind having the cycle count checked as a proxy, but I was primarily wondering about the "procedure" to follow here. If adjusting golden set occasionally after manually verifying that the change is "okay" then this is perfectly reasonable, question is what exactly is "okay" and how to determine. Intuitively I assume in this case the way the counts changed should not indicate major regression, but wanted to clarify.

I don't have a clear answer to what is a convenient and reasonable procedure. Since the HLS test suite no longer fails when the cycle count differs, it is possible to simply approve the PR if there are minor differences, especially if the cycles get reduced. The question then is when should the cycles in the test suite be updated.

Related to this, I've created a PR (https://github.com/phate/hls-test-suite/pull/20) that creates a comment when the cycles don't match. We will then get a comment for each PR if the cycles don't match without having to fail the test suite, and having to dig through the logs to see if there are any changes.

2025-01-05 19:38 UTC, phate approved these changes
I just skimmed the PR now. I already went through it 2-3 times, not much to say about it any longer.

Regarding the fix for the unbalance inputs/outputs: I would love to see it in another PR and not put this on top of that one as well. It is already big enough. I find it great that you found a sound solution. I suspect that we could also apply the same solution to phi nodes and the HLS loop node.

2025-01-05 19:38 UTC, phate commented on jlm/rvsdg/theta.hpp
> +
I normally put std library include files below the jlm include files. Is there a particular reason why you put them above, or just coincidence?

2025-01-06 19:16 UTC, caleridas commented on jlm/rvsdg/theta.hpp
> +
normally I do it in this order: C headers, C++ language headers, external C++ library headers, then project headers; rationale is that this is also the order of precedence / dependence

but sorted it as requested

2025-01-06 19:25 UTC, phate approved these changes

2025-01-06 19:38 UTC, merged