Adds additional cases for remove_redundant_buf optimization
phate/jlm pull request #682
Opened 2024-12-13 17:32 UTC by sjalander

2024-12-16 08:05 UTC, phate requested changes
Again, could we get some unit tests on this?

2024-12-16 08:05 UTC, phate commented on jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp
> +    else if (dynamic_cast<const jlm::hls::fork_op *>(&node->GetOperation()))
`is<>()`

2024-12-16 08:05 UTC, phate commented on jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp
> +    else if (dynamic_cast<const jlm::hls::load_op *>(&node->GetOperation()))
`is<>()`

2024-12-16 08:05 UTC, phate commented on jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp
> +    else if (dynamic_cast<const jlm::hls::store_op *>(&node->GetOperation()))
`is<>()`

2024-12-16 09:48 UTC, sjalander commented on jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp
> +    else if (dynamic_cast<const jlm::hls::load_op *>(&node->GetOperation()))
Changed

2024-12-16 09:48 UTC, sjalander commented on jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp
> +    else if (dynamic_cast<const jlm::hls::store_op *>(&node->GetOperation()))
Changed

2024-12-24 17:58 UTC, phate approved these changes
The unit tests were merged in another PR, right?

2024-12-25 07:42 UTC, sjalander commented
A unit test has not been created for this PR. The reason is that when I started looking into the functionality of this optimization, I'm not able to determine its purpose. The name seems to be somewhat misleading. From what I can tell, it replaces pass through buffers with non-pass through buffers in some specific cases. However, it doesn't seem to have an effect on the hls_test_suite as when I comment out the optimization, then I get no change in the number of cycles.

@davidmetz Do you have a use case where this optimization makes a difference?

2024-12-25 08:13 UTC, merged